---
- name: Get default interface name
  set_fact:
    default_ipv4_interface: "{{ ansible_default_ipv4.interface }}"

- name: Configure network interfaces
  include_tasks: interface.yml
  when: vswitch.ipv4_address is defined
  with_items: "{{ hetzner_vswitch_host }}"
  loop_control:
    loop_var: vswitch
