---
- name: Get default interface name
  set_fact:
    default_ipv4_interface: "{{ ansible_default_ipv4.interface }}"

- name: Ensure /etc/network/interfaces.d directory exists
  file:
    path: /etc/network/interfaces.d
    state: directory
    mode: '0755'

- name: Include /etc/network/interfaces.d files
  lineinfile:
    path:  /etc/network/interfaces
    regexp: "^{{ 'source /etc/network/interfaces.d/*' | regex_escape }}$"
    line: "source /etc/network/interfaces.d/*"

- name: Configure network interfaces
  include_tasks: interface/main.yml
  when: vswitch.ipv4_address is defined
  with_items: "{{ hetzner_vswitch_host }}"
  loop_control:
    loop_var: vswitch
