---
- name: Prepare Hetzner Robot Mock API
  hosts: localhost
  tasks:
    - name: Run Hetzner Robot Mock API Container
      shell: docker run -d --rm --network molecule --name hetzner-robot {{ hetzner_vswitch_webservice_mock }}
    - name: Create vSwitch template
      uri:
        url: "{{ hetzner_vswitch_hetzner_robot_api_url }}/vswitch"
        method: POST
        user: "{{ hetzner_vswitch_hetzner_robot_api_user }}"
        password: "{{ hetzner_vswitch_hetzner_robot_api_pass }}"
        status_code: 201
        body:
          vlan: "{{ hetzner_vswitch_vlan_id }}"  # The vSwitch for our VLAN is there, but was cancelled.
          name: "sib-mongo-germany"
          id: 3500
          cancelled: true
        force_basic_auth: yes
        body_format: json
