---
- name: Install required packages
  package:
    name:
      - iproute
      - ifupdown
    state: present

- name: Update network related host facts
  setup:
    gather_subset: '!all,!any,network'
