---
- name: Set handlers variable
  set_fact:
    hetzner_vswitch_handle: yes
  tags: ["hetzner_vswitch", "hetzner_vswitch_handle", "handle"]

- import_tasks: install.yml
  tags: ["hetzner_vswitch", "hetzner_vswitch_install", "install"]

- import_tasks: vswitch/main.yml
  delegate_to: localhost
  run_once: yes
  tags: ["hetzner_vswitch", "hetzner_vswitch_config", "hetzner_vswitch_vswitch", "config"]

- import_tasks: vswitch_server/main.yml
  delegate_to: localhost
  run_once: yes
  tags:  ["hetzner_vswitch", "hetzner_vswitch_config", "hetzner_vswitch_vswitch_server", "config"]

- include_tasks: host_network/main.yml
  tags: ["hetzner_vswitch", "hetzner_vswitch_config", "hetzner_vswitch_host", "config"]
