---
- name: Stop network interface
  changed_when: no
  command: "ifdown {{ interface_name }}"
  when: interface_name in ip_link_list_result.stdout

- name: Delete IP link
  changed_when: no
  command: "ip link delete {{ interface_name }}"
  when: interface_name in ip_link_list_result.stdout

- name: "Remove virtual interface {{ interface_name }}"
  file:
    path: "/etc/network/interfaces.d/{{ interface_name }}"
    state: absent

- name: Remove if-up script
  file:
    path: "/etc/network/interfaces.d/{{ interface_file_name }}"
    state: absent
