---
- name: "Configure virtual interface {{ interface_name }}"
  template:
    src: templates/network/interface.j2
    dest: "/etc/network/interfaces.d/{{ interface_name }}"
  notify: restart network interface
