---
- name: "Configure virtual interface {{ interface_name }}"
  template:
    src: templates/network/interface.j2
    dest: "/etc/network/interfaces.d/{{ interface_name }}"
  notify: restart network interface

- name: Ensure /etc/network/if-up.d is present
  file:
    path: /etc/network/if-up.d
    state: directory

- name: Configure if-up script
  template:
    src: templates/network/if-up.j2
    dest: "/etc/network/if-up.d/{{ interface_file_name }}"
    mode: 0755
  notify: restart network interface
