---
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu-16
    image: ubuntu:16.04
    dockerfile: ../resources/playbooks/Dockerfile.j2
    groups:
      - platforms
provisioner:
  name: ansible
  inventory:
    group_vars:
      platforms:
        hetzner_vswitch_host:
          - name: Existing vSwitch
      all:
        hetzner_vswitch_webservice_base_url: http://hetzner-robot:3000
        hetzner_vswitch_webservice_base_username: robot
        hetzner_vswitch_webservice_base_password: secret
        hetzner_vswitch_webservice_mock: nl2go/hetzner-robot-api-mock:1.3.2
        hetzner_vswitch_instances:
          - name: Existing vSwitch
  lint:
    name: ansible-lint
  playbooks:
    converge: ../resources/playbooks/playbook.yml
    cleanup: ../resources/playbooks/cleanup.yml
verifier:
  name: ansible
  lint:
    name: ansible-lint
